name: Deploy to AWS Production
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./application/client

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./application/client/package-lock.json"
          clean: false
      - run: npm ci
      - run: npm run build:dev
      - run: sudo systemctl stop nginx
      - run: sudo systemctl start nginx

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          clean: false
      - name: Run Python commands
        env:
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_PASSWORD: ${{ secrets.AWS_PASSWORD }}
          AWS_DB_HOSTNAME: ${{ secrets.AWS_DB_HOSTNAME }}
          AWS_DB_NAME: ${{ secrets.AWS_DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cp /home/ubuntu/.env api/.env
          touch api/.test
          echo "AWS_USERNAME=$AWS_USERNAME" >> api/.test
          echo "AWS_PASSWORD=$AWS_PASSWORD" >> api/.test
          echo "AWS_DB_HOSTNAME=$AWS_DB_HOSTNAME" >> api/.test
          echo "AWS_DB_NAME=$AWS_DB_NAME" >> api/.test
          echo "SECRET_KEY=$SECRET_KEY" >> api/.test
          pip install --upgrade pip
          python3 -m venv api/env
          source api/env/bin/activate
          pip3 install -r api/requirements.txt
          deactivate
          sudo systemctl stop debugme
          sudo systemctl start debugme
