name: Deploy to AWS Production
on:
  push:
    branches: ["master"]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Milestones/M3/HorizontalPrototype/client

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./Milestones/M3/HorizontalPrototype/client/package-lock.json"
          clean: false
      - run: npm ci
      - run: npm run build --if-present
      - run: sudo systemctl stop nginx
      - run: sudo systemctl start nginx

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          clean: false
      - name: Run Python commands
        run: |
          echo "${{ secrets.debugme }}" > api/.env
          pip install --upgrade pip
          python3 -m venv api/env
          source api/env/bin/activate
          pip3 install -r api/requirements.txt
          deactivate
          sudo systemctl stop debugme
          sudo systemctl start debugme

  # backend:
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       working-directory: ./Milestones/M3/HorizontalPrototype/client

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.10
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
  #     - name: Run Python commands
  #       run: |
  #         pip install --upgrade pip
  #         python3 -m venv api/env
  #         source api/env/bin/activate
  #         pip3 install -r api/requirements.txt
  #         deactivate
  #         sudo systemctl stop debugme
  #         sudo systemctl start debugme

  # verticalPrototype:
  #   name: Build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: executing remote ssh commands using password
  #     uses: appleboy/ssh-action@v0.1.10
  #     with:
  #       host: ${{ secrets.AWS_PROTOTYPES }}
  #       username: ${{ secrets.USERNAME }}
  #       password: ${{ secrets.PRIVATE_KEY }}
  #       port: ${{ secrets.AWS_PORT }}
  #       script: whoami
